using System;

// Note: 'Code First' - we create code and from that we create scripts that create the db.
namespace Domain
{
    public class Value
    {
        public int Id { get; set; } // Entity Framework will use 'Id' as primary key. Because it is an int and DB supports autogenerated properties then this will configure DB when used to use autogenerated number.
        
        public string Name { get; set; }
    }
}
